class HarleyDavidsonX{
	
	
	//static variable
	static String brand = "HARLEY-DAVIDSON X";
	static String model = "HX44BMDSCFITRD";
	static String colour = "Metallic Thick Red";
	static int engineCapacity = 440;
	static int power = 27;
	static int torque = 38;
	static int fuelTankCapacity = 13;
	static int saddleHeight = 805;
	static double kerbWeight = 190.5;
	static int modelYear = 2025;
	
public static void main(String[] args){

	//local variable
	/*String brand = "HARLEY-DAVIDSON X";
	String model = "HX44BMDSCFITRD";
	String colour = "Metallic Thick Red";
	int engineCapacity = 440;
	int power = 27;
	int torque = 38;
	int fuelTankCapacity = 13;
	int saddleHeight = 805;
	double kerbWeight = 190.5;
	int modelYear = 2025;*/

	System.out.println("Which brand does this motorcycle belong to? " + brand);
	System.out.println("What is the official model code of the motorcycle? " + model);
	System.out.println("Which colour variant is available for this model? " + colour);
	System.out.println("What is the engine capacity of this motorcycle? " + engineCapacity + " cc");
	System.out.println("How much maximum power does the engine produce? " + power + " bhp");
	System.out.println("What is the peak torque generated by the engine? " + torque + " Nm");
	System.out.println("What is the total fuel tank capacity of the bike? " + fuelTankCapacity + " L");
	System.out.println("What is the saddle height provided for the rider? " + saddleHeight + " mm");
	System.out.println("How much does the motorcycle weigh in kerb condition? " + kerbWeight + " kg");
	System.out.println("Which model year does this motorcycle belong to? " + modelYear);

}
}
